#!/usr/bin/env python3
"""Generate worlds/building.world: 12 x 10 m building, 4 rooms, 6 ArUco markers.

Coordinates are world = map frame after SLAM if the robot starts at the spawn pose
used for mapping. Edit WALLS / OBSTACLES / MARKERS and re-run.
"""
import math
import os

WALL_T = 0.15   # wall thickness [m]
WALL_H = 1.0    # wall height [m]
MARKER_Z = 0.25 # marker centre height [m]

# (name, cx, cy, sx, sy)  axis-aligned wall boxes
WALLS = [
    ('outer_n', 0.0, 5.0, 12.15, WALL_T),
    ('outer_s', 0.0, -5.0, 12.15, WALL_T),
    ('outer_e', 6.0, 0.0, WALL_T, 10.15),
    ('outer_w', -6.0, 0.0, WALL_T, 10.15),
    # vertical wall x=0, doors at y in [1.5, 2.7] and [-3.9, -2.7]
    ('mid_v_top', 0.0, 3.85, WALL_T, 2.3),
    ('mid_v_mid', 0.0, -0.6, WALL_T, 4.2),
    ('mid_v_bot', 0.0, -4.45, WALL_T, 1.1),
    # horizontal wall y=0 (left half), door at x in [-3.6, -2.4]
    ('left_h_w', -4.8, 0.0, 2.4, WALL_T),
    ('left_h_e', -1.2, 0.0, 2.4, WALL_T),
    # horizontal wall y=-1 (right half), door at x in [2.4, 3.6]
    ('right_h_w', 1.2, -1.0, 2.4, WALL_T),
    ('right_h_e', 4.8, -1.0, 2.4, WALL_T),
]

# (name, cx, cy, sx, sy, height)
OBSTACLES = [
    ('pillar', 3.5, 2.5, 0.4, 0.4, WALL_H),
    ('crate', -4.5, -3.5, 0.8, 0.5, 0.5),
]

# (id, x, y, yaw)  marker centre sits on the wall surface, face normal along +-model X
_off = WALL_T / 2 + 0.005
MARKERS = [
    (0, -4.0, 5.0 - _off, math.pi / 2),    # top-left room, north wall
    (1, 6.0 - _off, 3.0, 0.0),             # top-right room, east wall
    (2, 4.0, -5.0 + _off, math.pi / 2),    # bottom-right room, south wall
    (3, -6.0 + _off, -2.0, 0.0),           # bottom-left room, west wall
    (4, 1.2, -1.0 - _off, math.pi / 2),    # bottom-right room, wall y=-1 south face
    (5, -1.2, 0.0 + _off, math.pi / 2),    # top-left room, wall y=0 north face
]


def box_link(name, cx, cy, sx, sy, h, color):
    size = f'{sx} {sy} {h}'
    return f"""
      <link name="{name}">
        <pose>{cx} {cy} {h / 2} 0 0 0</pose>
        <collision name="collision"><geometry><box><size>{size}</size></box></geometry></collision>
        <visual name="visual">
          <geometry><box><size>{size}</size></box></geometry>
          <material><script><uri>file://media/materials/scripts/gazebo.material</uri><name>{color}</name></script></material>
        </visual>
      </link>"""


def main():
    links = ''.join(box_link(n, x, y, sx, sy, WALL_H, 'Gazebo/Grey') for n, x, y, sx, sy in WALLS)
    links += ''.join(box_link(n, x, y, sx, sy, h, 'Gazebo/Wood') for n, x, y, sx, sy, h in OBSTACLES)
    markers = ''.join(f"""
    <include>
      <name>aruco_{i}</name>
      <uri>model://aruco_{i}</uri>
      <pose>{x:.3f} {y:.3f} {MARKER_Z} 0 0 {yaw:.6f}</pose>
    </include>""" for i, x, y, yaw in MARKERS)

    world = f"""<?xml version="1.0"?>
<!-- Generated by scripts/generate_world.py -->
<sdf version="1.6">
  <world name="sar_building">
    <include><uri>model://sun</uri></include>
    <include><uri>model://ground_plane</uri></include>

    <physics type="ode">
      <real_time_update_rate>1000.0</real_time_update_rate>
      <max_step_size>0.001</max_step_size>
    </physics>

    <gui>
      <camera name="user_camera">
        <pose>0 0 17 0 1.5707 0</pose>
      </camera>
    </gui>

    <model name="building">
      <static>true</static>{links}
    </model>
{markers}
  </world>
</sdf>
"""
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'worlds', 'building.world')
    with open(out, 'w') as f:
        f.write(world)
    print(f'Wrote {os.path.abspath(out)}')
    for i, x, y, _ in MARKERS:
        print(f'  aruco_{i}: x={x:+.3f} y={y:+.3f}  (ground truth)')


if __name__ == '__main__':
    main()
